function resize(){D=Math.min(2,devicePixelRatio||1);W=innerWidth;H=innerHeight;c.width=W*D;c.height=H*D;ctx.setTransform(D,0,0,D,0,0)}addEventListener('resize',resize);
function toast(t){let e=$('#toast');e.textContent=t;e.style.opacity=1;clearTimeout(toast.t);toast.t=setTimeout(()=>e.style.opacity=0,1200)}
function hud(){ $('#money').textContent=S.money;$('#fuel').textContent=Math.floor(S.fuel);$('#fuelmax').textContent=S.fuelMax;$('#bag').textContent=S.bag.length;$('#bagmax').textContent=S.bagCap;$('#area').textContent=S.map==='island'?'HOME ISLAND':S.map==='sea'?'OPEN SEA':`ABYSS FLOOR ${S.map.split('-')[1]}`;let q=['Catch 3 harbor creatures and sell them to Silas.','Donate 500 coins to rebuild the General Store.','Buy the Boat Key from the General Store.','Launch the dinghy and reach the Outer Reef.','Upgrade your boat for offshore waters.','Acquire the Mini Submarine and descend.','Explore the Abyss Floors.'];$('#quest').textContent='QUEST: '+q[Math.min(S.quest,q.length-1)]}
function waterTile(tx,ty){if(S.map==='sea')return true;if(S.map.startsWith('abyss'))return false;let dx=tx-16,dy=ty-14;return dx*dx/210+dy*dy/150>1}
function solid(tx,ty){if(tx<0||ty<0||tx>=MAPW||ty>=MAPH)return true;if(S.map==='island'){if(waterTile(tx,ty))return true;let buildings=[[6,6,6,5],[20,6,6,5],[22,17,5,4]];for(let b of buildings)if(tx>=b[0]&&tx<b[0]+b[2]&&ty>=b[1]&&ty<b[1]+b[3])return true}return false}
function drawTile(px,py,col){ctx.fillStyle=col;ctx.fillRect(Math.floor(px),Math.floor(py),TS+1,TS+1)}
function pixText(t,x,y,col='#fff'){ctx.fillStyle='#071018';ctx.font='bold 11px monospace';ctx.fillText(t,x+1,y+1);ctx.fillStyle=col;ctx.fillText(t,x,y)}
function grassTuft(x,y){ctx.fillStyle='#3e7c47';ctx.fillRect(x,y+4,2,5);ctx.fillRect(x+4,y+2,2,7);ctx.fillStyle='#8fc86c';ctx.fillRect(x+2,y,2,6)}
function rock(x,y){ctx.fillStyle='#51645d';ctx.fillRect(x+2,y+3,12,8);ctx.fillStyle='#788b80';ctx.fillRect(x+4,y+1,8,5);ctx.fillStyle='#263934';ctx.fillRect(x+3,y+10,10,3)}
function tree(x,y){ctx.fillStyle='#5f412d';ctx.fillRect(x+9,y+20,7,15);ctx.fillStyle='#244f3c';ctx.fillRect(x+2,y+5,22,18);ctx.fillStyle='#3d7650';ctx.fillRect(x,y+9,26,10);ctx.fillStyle='#65a765';ctx.fillRect(x+5,y+1,16,12);ctx.fillStyle='#86c078';ctx.fillRect(x+8,y+3,5,5)}
function building(tx,ty,w,h,roof,label,open=true){let x=tx*TS-cam.x,y=ty*TS-cam.y;ctx.fillStyle='#0005';ctx.fillRect(x+5,y+h*TS-7,w*TS,10);ctx.fillStyle=open?'#d8c597':'#a79b82';ctx.fillRect(x,y+TS,w*TS,h*TS-TS);ctx.fillStyle='#7b6247';for(let yy=y+TS+8;yy<y+h*TS;yy+=12){ctx.fillRect(x+3,yy,w*TS-6,2)}ctx.fillStyle=roof;ctx.fillRect(x-5,y,w*TS+10,TS+10);ctx.fillStyle='#ffffff18';ctx.fillRect(x,y+4,w*TS-2,4);ctx.fillStyle='#4b2f2b';ctx.fillRect(x+w*TS/2-10,y+h*TS-25,20,25);ctx.fillStyle='#e7c56a';ctx.fillRect(x+w*TS/2-5,y+h*TS-18,4,4);ctx.fillStyle='#8ec4d1';ctx.fillRect(x+14,y+TS+15,18,14);ctx.fillRect(x+w*TS-32,y+TS+15,18,14);ctx.fillStyle='#d8eadc';ctx.fillRect(x+16,y+TS+17,14,2);ctx.fillRect(x+w*TS-30,y+TS+17,14,2);pixText(label,x+5,y+17,open?'#fff':'#bbb')}
function drawIsland(){const tm=performance.now()/500;for(let y=0;y<MAPH;y++)for(let x=0;x<MAPW;x++){let water=waterTile(x,y),px=x*TS-cam.x,py=y*TS-cam.y;if(water){let shade=((x+y+Math.floor(tm))%3);drawTile(px,py,shade===0?'#2d7892':shade===1?'#317f9b':'#3487a1');ctx.fillStyle='#ffffff16';if((x*7+y*3+Math.floor(tm))%9===0)ctx.fillRect(px+5,py+8,10,2)}else{drawTile(px,py,((x*3+y)%5?'#6fa958':'#7db765'));if(((x*11+y*7)%17)===0)grassTuft(px+7,py+8)}}ctx.strokeStyle='#d9c77c';ctx.lineWidth=3;ctx.globalAlpha=.65;ctx.beginPath();ctx.ellipse(16*TS-cam.x,14*TS-cam.y,Math.sqrt(210)*TS*.93,Math.sqrt(150)*TS*.93,0,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1;[[4,10],[5,14],[8,18],[24,13],[27,14],[19,4],[13,5],[4,16]].forEach(a=>tree(a[0]*TS-cam.x,a[1]*TS-cam.y));[[12,8],[18,9],[7,20],[25,20],[15,19]].forEach(a=>rock(a[0]*TS-cam.x+4,a[1]*TS-cam.y+8));building(6,6,6,5,'#a45a43','GENERAL STORE',S.store);building(20,6,6,5,'#586d79','WORKSHOP',S.workshop);building(22,17,5,4,'#6f4e3f','LOCKED',false);ctx.fillStyle='#6e4f35';ctx.fillRect(12*TS-cam.x,22*TS-cam.y,8*TS,2*TS);ctx.fillStyle='#a97a4c';for(let i=0;i<8;i++)ctx.fillRect((12+i)*TS-cam.x+2,22*TS-cam.y+3,TS-4,8);npc(15,13,'SILAS','#d4a04e');npc(10,10,'MIRA','#a15b72')}
function drawSea(){for(let y=0;y<MAPH;y++)for(let x=0;x<MAPW;x++)drawTile(x*TS-cam.x,y*TS-cam.y,((x+y)%3?'#176480':'#1b6d88'));for(let i=0;i<14;i++){let x=(i*83+60)%760-cam.x,y=(i*137+90)%650-cam.y;ctx.fillStyle='#5c9e6c';ctx.fillRect(x,y,TS*2,TS);ctx.fillStyle='#d6c47e';ctx.fillRect(x+8,y+TS,TS,8)}}
function drawAbyss(){let floor=+S.map.split('-')[1];for(let y=0;y<MAPH;y++)for(let x=0;x<MAPW;x++)drawTile(x*TS-cam.x,y*TS-cam.y,(x+y)%2?(floor%2?'#172a39':'#2b2138'):(floor%2?'#1b3242':'#332743'));for(let i=0;i<25;i++){ctx.fillStyle=i%3?'#466d68':'#805b86';ctx.fillRect((i*79)%760-cam.x,(i*113)%650-cam.y,8,18)}}
function npc(x,y,name,col){let px=x*TS-cam.x,py=y*TS-cam.y;ctx.fillStyle='#0005';ctx.fillRect(px+5,py+21,15,4);ctx.fillStyle=col;ctx.fillRect(px+6,py+8,12,13);ctx.fillStyle='#26353e';ctx.fillRect(px+5,py+20,6,4);ctx.fillRect(px+14,py+20,6,4);ctx.fillStyle='#e7c9a5';ctx.fillRect(px+7,py+1,10,9);ctx.fillStyle='#49342c';ctx.fillRect(px+7,py,10,3);pixText(name,px-6,py-5,'#ffe27b')}
function player(){let x=S.x*TS-cam.x,y=S.y*TS-cam.y,bob=Math.sin(performance.now()/120)*.7;ctx.fillStyle='#0005';ctx.fillRect(x+4,y+21,16,4);ctx.fillStyle='#1d405c';ctx.fillRect(x+5,y+8+bob,14,13);ctx.fillStyle='#2d5877';ctx.fillRect(x+6,y+10+bob,12,4);ctx.fillStyle='#26333a';ctx.fillRect(x+4,y+20+bob,6,4);ctx.fillRect(x+14,y+20+bob,6,4);ctx.fillStyle='#e5bd91';ctx.fillRect(x+7,y+1+bob,10,9);ctx.fillStyle='#b33e38';ctx.fillRect(x+5,y+bob,14,4);ctx.fillStyle='#f2d77d';ctx.fillRect(x+16,y+2+bob,4,2)}
function boat(){if(S.map!=='sea')return;let x=S.x*TS-cam.x,y=S.y*TS-cam.y,b=Math.sin(performance.now()/300)*1.2;ctx.fillStyle='#0004';ctx.fillRect(x-2,y+19,28,5);ctx.fillStyle='#5e3d2c';ctx.fillRect(x+1,y+9+b,22,10);ctx.fillStyle='#a16946';ctx.fillRect(x+4,y+6+b,16,6);ctx.fillStyle='#e7dfc6';ctx.fillRect(x+10,y-5+b,3,12);ctx.fillRect(x+13,y-3+b,9,7);ctx.fillStyle='#2d596a';ctx.fillRect(x+15,y-1+b,4,3)}
function render(){cam.x=Math.max(0,Math.min(MAPW*TS-W,S.x*TS-W/2));cam.y=Math.max(0,Math.min(MAPH*TS-H,S.y*TS-H/2));ctx.fillStyle='#08131a';ctx.fillRect(0,0,W,H);if(S.map==='island')drawIsland();else if(S.map==='sea')drawSea();else drawAbyss();S.map==='sea'?boat():player();if(fishing){ctx.fillStyle='#fff';ctx.fillRect(W/2-2,H/2-55,4,35);ctx.fillStyle=bite>0?'#f1d36b':'#fff';ctx.fillRect(W/2-5,H/2-63,10,8);pixText(bite>0?'! BITE !':'FISHING...',W/2-32,H/2-78,'#ffe27b')}}
function zone(){if(S.map==='island')return 0;if(S.map==='sea')return Math.min(4,Math.max(1,S.boat));return Math.min(6,4+Math.floor(+S.map.split('-')[1]/3))}
function catchFish(){let z=zone(),pool=FISH.filter(f=>f.zone<=z&&f.zone>=Math.max(0,z-1));let f=pool[Math.floor(Math.random()*pool.length)];if(S.bag.length>=S.bagCap)return toast('Your pack is full.');S.bag.push(f);S.caught++;fishing=false;bite=0;toast('Caught: '+f.name+'  $'+f.value);if(S.quest===0&&S.caught>=3)S.quest=1;hud()}
function action(){if(fishing){if(bite>0)catchFish();else{fishing=false;toast('Pulled too early.')}return}if(S.map==='island'){let ds=Math.hypot(S.x-15,S.y-13);if(ds<2)return seller();if(Math.hypot(S.x-9,S.y-11)<3)return store();if(Math.hypot(S.x-23,S.y-11)<3)return workshop();if(S.y>21&&S.x>11&&S.x<21){if(!S.owned.includes('Boat Key'))return toast('The boat is locked.');S.map='sea';S.x=16;S.y=22;S.fuel=S.fuelMax||60;S.boat=Math.max(1,S.boat);S.quest=Math.max(3,S.quest);hud();return}startFishing()}else if(S.map==='sea'){if(S.y>25){S.map='island';S.x=16;S.y=21;hud();return}if(S.sub&&S.x<5&&S.y<5){S.map='abyss-1';S.x=16;S.y=22;S.quest=6;hud();return}startFishing()}else{startFishing()}}
function startFishing(){if(S.bag.length>=S.bagCap)return toast('Pack full. Sell your catch.');fishing=true;bite=0;setTimeout(()=>{if(fishing){bite=1;toast('BITE! Tap A!')}},700+Math.random()*1400)}
function seller(){let total=S.bag.reduce((a,f)=>a+f.value,0);let body=`<h2>SILAS — FISH BUYER</h2><p>“Bring me anything that swims, crawls or should probably have stayed down there.”</p><p>Your catch: <b>${S.bag.length}</b><br>Offer: <b>$${total}</b></p><button onclick="sellAll()">SELL EVERYTHING</button>`;if(!S.store)body+=`<p>The old General Store can reopen if someone funds the repairs.</p><button onclick="donate()">DONATE $500</button>`;modal(body)}
function sellAll(){let total=S.bag.reduce((a,f)=>a+f.value,0);S.money+=total;S.bag=[];closeM();toast('Sold catch for $'+total);hud()}
function donate(){if(S.money<500)return toast('Need $500.');S.money-=500;S.store=true;S.quest=Math.max(2,S.quest);closeM();toast('GENERAL STORE UNLOCKED!');hud()}
function store(){if(!S.store)return modal('<h2>GENERAL STORE — UNDER CONSTRUCTION</h2><p>A faded sign reads: REPAIRS NEEDED — $500.</p>');shop('GENERAL STORE',ITEMS.filter(i=>['rod','knife','bag','key','fuel','trap','tool','consumable','charm','map'].includes(i.type)&&i.tier<=Math.max(2,S.boat+1)))}
function workshop(){if(!S.workshop){if(S.money>=1800)return modal('<h2>OLD WORKSHOP</h2><p>The shipwright could reopen this place for $1,800.</p><button onclick="openWorkshop()">FUND WORKSHOP $1800</button>');return modal('<h2>OLD WORKSHOP</h2><p>Locked. A chalk note says: “Come back when you can afford to build something worth sailing.”</p>')}shop('HARBOR WORKSHOP',ITEMS.filter(i=>['boat','engine','sonar','sub','weapon'].includes(i.type)))}
function openWorkshop(){S.money-=1800;S.workshop=true;closeM();toast('WORKSHOP UNLOCKED');hud()}
function shop(title,list){let h='<h2>'+title+'</h2><div class="grid">';for(let i of list){let own=S.owned.includes(i.name);h+=`<div class="item"><b>${i.name}</b>${i.type.toUpperCase()} · T${i.tier}<br>$${i.price}<button ${own?'disabled':''} onclick='buy(${JSON.stringify(i.name)})'>${own?'OWNED':'BUY'}</button></div>`}h+='</div>';modal(h)}
function buy(name){let i=ITEMS.find(x=>x.name===name);if(S.money<i.price)return toast('Not enough money.');S.money-=i.price;S.owned.push(name);if(i.type==='bag')S.bagCap+=6;if(i.type==='rod')S.rod=Math.max(S.rod,i.tier);if(i.type==='knife')S.knife=Math.max(S.knife,i.tier);if(i.type==='weapon')S.weapon=Math.max(S.weapon,i.tier);if(i.name==='Boat Key'){S.fuelMax=60;S.quest=Math.max(3,S.quest)}if(i.type==='boat'){S.boat=Math.max(S.boat,i.tier);S.fuelMax=60+i.tier*45;S.quest=Math.max(4,S.quest)}if(i.name==='Mini Submarine'){S.sub=true;S.quest=5}if(i.type==='fuel')S.fuel=Math.min(S.fuelMax,S.fuel+(i.name==='Fuel Can'?35:80));hud();closeM();toast('Bought '+name)}
function inventory(){let owned=S.owned.map(n=>'<div class="item"><b>'+n+'</b></div>').join('');let catchs=S.bag.map(f=>'<div class="item"><b>'+f.name+'</b>$'+f.value+'</div>').join('');modal(`<h2>PACK</h2><p>Gear (${S.owned.length}/${ITEMS.length})</p><div class="grid">${owned}</div><p>Catch</p><div class="grid">${catchs||'<div class="item">Empty</div>'}</div>`)}
function modal(h){$('#modal').innerHTML=h+'<button class="close" onclick="closeM()">CLOSE</button>';$('#mw').style.display='flex'}function closeM(){$('#mw').style.display='none'}
function step(dx,dy){if(fishing)return;let nx=S.x+dx*.085,ny=S.y+dy*.085;if(S.map==='sea'){let cost=.12*(1+Math.max(0,S.boat-1)*.12);if(S.fuel<=0)return toast('OUT OF FUEL');S.fuel=Math.max(0,S.fuel-cost);S.x=clamp(nx,.5,MAPW-1.5);S.y=clamp(ny,.5,MAPH-1.5)}else if(!solid(Math.floor(nx),Math.floor(ny))){S.x=nx;S.y=ny}hud()}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
const joyEl=$('#joy'),joyKnob=$('#joyKnob');let joyState={active:false,id:null,cx:0,cy:0,dx:0,dy:0};function joyStart(e){e.preventDefault();joyState.active=true;joyState.id=e.pointerId;let r=joyEl.getBoundingClientRect();joyState.cx=r.left+r.width/2;joyState.cy=r.top+r.height/2;joyMove(e);joyEl.setPointerCapture?.(e.pointerId)}function joyMove(e){if(!joyState.active||e.pointerId!==joyState.id)return;e.preventDefault();let dx=e.clientX-joyState.cx,dy=e.clientY-joyState.cy,m=39,l=Math.hypot(dx,dy);if(l>m){dx*=m/l;dy*=m/l}joyState.dx=dx/m;joyState.dy=dy/m;joyKnob.style.transform=`translate(${dx}px,${dy}px)`}function joyEnd(e){if(e&&joyState.id!==null&&e.pointerId!==joyState.id)return;joyState.active=false;joyState.dx=joyState.dy=0;joyKnob.style.transform='translate(0,0)'}joyEl.addEventListener('pointerdown',joyStart,{passive:false});joyEl.addEventListener('pointermove',joyMove,{passive:false});joyEl.addEventListener('pointerup',joyEnd);joyEl.addEventListener('pointercancel',joyEnd);document.addEventListener('contextmenu',e=>e.preventDefault());document.addEventListener('selectstart',e=>e.preventDefault());
$('#act').onclick=action;$('#inv').onclick=inventory;$('#go').onclick=()=>{$('#start').style.display='none';hud();last=performance.now();requestAnimationFrame(loop)};function loop(t){if(joyState.active){let mag=Math.hypot(joyState.dx,joyState.dy);if(mag>.08)step(joyState.dx,joyState.dy)}render();requestAnimationFrame(loop)}resize();hud();
document.addEventListener('dragstart',e=>e.preventDefault());