function resize(){D=Math.min(2,devicePixelRatio||1);W=innerWidth;H=innerHeight;c.width=W*D;c.height=H*D;ctx.setTransform(D,0,0,D,0,0)}addEventListener('resize',resize);
function toast(t){let e=$('#toast');e.textContent=t;e.style.opacity=1;clearTimeout(toast.t);toast.t=setTimeout(()=>e.style.opacity=0,1100)}
function hud(){money.textContent=S.money;fuel.textContent=Math.floor(S.fuel);fuelmax.textContent=S.fuelMax;bag.textContent=S.bag.length;bagmax.textContent=S.bagCap;area.textContent=S.map==='island'?'HOME ISLAND':S.map==='sea'?'OPEN SEA':`ABYSS FLOOR ${S.map.split('-')[1]}`;let q=['Catch 3 harbor creatures and sell them to Silas.','Donate 500 coins to rebuild the General Store.','Buy the Boat Key from the General Store.','Launch the dinghy and reach the Outer Reef.','Upgrade your boat for offshore waters.','Acquire the Mini Submarine and descend.','Explore the Abyss Floors.'];quest.textContent='QUEST: '+q[Math.min(S.quest,q.length-1)]}
function waterTile(tx,ty){if(S.map==='sea')return true;if(S.map.startsWith('abyss'))return false;let dx=tx-16,dy=ty-14;return dx*dx/210+dy*dy/150>1}
function solid(tx,ty){if(tx<0||ty<0||tx>=MAPW||ty>=MAPH)return true;if(S.map==='island'){if(waterTile(tx,ty))return true;for(let b of [[6,6,6,5],[20,6,6,5],[22,17,5,4]])if(tx>=b[0]&&tx<b[0]+b[2]&&ty>=b[1]&&ty<b[1]+b[3])return true}return false}
function drawTile(px,py,col){ctx.fillStyle=col;ctx.fillRect(px|0,py|0,TS+1,TS+1)}
function pixText(t,x,y,col='#fff',size=11){ctx.font=`bold ${size}px monospace`;ctx.fillStyle='#071018';ctx.fillText(t,x+1,y+1);ctx.fillStyle=col;ctx.fillText(t,x,y)}
function grassTuft(x,y){ctx.fillStyle='#3e7c47';ctx.fillRect(x,y+4,2,5);ctx.fillRect(x+4,y+2,2,7);ctx.fillStyle='#8fc86c';ctx.fillRect(x+2,y,2,6)}
function rock(x,y){ctx.fillStyle='#51645d';ctx.fillRect(x+2,y+3,12,8);ctx.fillStyle='#788b80';ctx.fillRect(x+4,y+1,8,5);ctx.fillStyle='#263934';ctx.fillRect(x+3,y+10,10,3)}
function tree(x,y){ctx.fillStyle='#5f412d';ctx.fillRect(x+9,y+20,7,15);ctx.fillStyle='#244f3c';ctx.fillRect(x+2,y+5,22,18);ctx.fillStyle='#3d7650';ctx.fillRect(x,y+9,26,10);ctx.fillStyle='#65a765';ctx.fillRect(x+5,y+1,16,12);ctx.fillStyle='#86c078';ctx.fillRect(x+8,y+3,5,5)}
function building(tx,ty,w,h,roof,label,open=true){let x=tx*TS-cam.x,y=ty*TS-cam.y;ctx.fillStyle='#0005';ctx.fillRect(x+5,y+h*TS-7,w*TS,10);ctx.fillStyle=open?'#d8c597':'#a79b82';ctx.fillRect(x,y+TS,w*TS,h*TS-TS);ctx.fillStyle='#7b6247';for(let yy=y+TS+8;yy<y+h*TS;yy+=12)ctx.fillRect(x+3,yy,w*TS-6,2);ctx.fillStyle=roof;ctx.fillRect(x-5,y,w*TS+10,TS+10);ctx.fillStyle='#ffffff18';ctx.fillRect(x,y+4,w*TS-2,4);ctx.fillStyle='#4b2f2b';ctx.fillRect(x+w*TS/2-10,y+h*TS-25,20,25);ctx.fillStyle='#e7c56a';ctx.fillRect(x+w*TS/2-5,y+h*TS-18,4,4);ctx.fillStyle='#8ec4d1';ctx.fillRect(x+14,y+TS+15,18,14);ctx.fillRect(x+w*TS-32,y+TS+15,18,14);pixText(label,x+5,y+17,open?'#fff':'#bbb')}
function npc(x,y,name,col){let px=x*TS-cam.x,py=y*TS-cam.y;ctx.fillStyle='#0005';ctx.fillRect(px+5,py+21,15,4);ctx.fillStyle=col;ctx.fillRect(px+6,py+8,12,13);ctx.fillStyle='#26353e';ctx.fillRect(px+5,py+20,6,4);ctx.fillRect(px+14,py+20,6,4);ctx.fillStyle='#e7c9a5';ctx.fillRect(px+7,py+1,10,9);ctx.fillStyle='#49342c';ctx.fillRect(px+7,py,10,3);pixText(name,px-6,py-5,'#ffe27b')}
function drawIsland(){let tm=performance.now()/500;for(let y=0;y<MAPH;y++)for(let x=0;x<MAPW;x++){let w=waterTile(x,y),px=x*TS-cam.x,py=y*TS-cam.y;if(w){let sh=(x+y+Math.floor(tm))%3;drawTile(px,py,sh===0?'#2d7892':sh===1?'#317f9b':'#3487a1');ctx.fillStyle='#ffffff16';if((x*7+y*3+Math.floor(tm))%9===0)ctx.fillRect(px+5,py+8,10,2)}else{drawTile(px,py,(x*3+y)%5?'#6fa958':'#7db765');if((x*11+y*7)%17===0)grassTuft(px+7,py+8)}}[[4,10],[5,14],[8,18],[24,13],[27,14],[19,4],[13,5],[4,16]].forEach(a=>tree(a[0]*TS-cam.x,a[1]*TS-cam.y));[[12,8],[18,9],[7,20],[25,20],[15,19]].forEach(a=>rock(a[0]*TS-cam.x+4,a[1]*TS-cam.y+8));building(6,6,6,5,'#a45a43','GENERAL STORE',S.store);building(20,6,6,5,'#586d79','WORKSHOP',S.workshop);building(22,17,5,4,'#6f4e3f','LOCKED',false);ctx.fillStyle='#6e4f35';ctx.fillRect(12*TS-cam.x,22*TS-cam.y,8*TS,2*TS);ctx.fillStyle='#a97a4c';for(let i=0;i<8;i++)ctx.fillRect((12+i)*TS-cam.x+2,22*TS-cam.y+3,TS-4,8);npc(15,13,'SILAS','#d4a04e');npc(10,10,'MIRA','#a15b72')}
function drawSea(){let tm=performance.now()/450;for(let y=0;y<MAPH;y++)for(let x=0;x<MAPW;x++){drawTile(x*TS-cam.x,y*TS-cam.y,(x+y+Math.floor(tm))%3?'#176480':'#1b718d');ctx.fillStyle='#ffffff12';if((x*5+y*7+Math.floor(tm))%13===0)ctx.fillRect(x*TS-cam.x+4,y*TS-cam.y+7,13,2)}for(let i=0;i<14;i++){let x=(i*83+60)%760-cam.x,y=(i*137+90)%650-cam.y;ctx.fillStyle='#5c9e6c';ctx.fillRect(x,y,TS*2,TS);ctx.fillStyle='#d6c47e';ctx.fillRect(x+8,y+TS,TS,8)}}
function drawAbyss(){let f=+S.map.split('-')[1];for(let y=0;y<MAPH;y++)for(let x=0;x<MAPW;x++)drawTile(x*TS-cam.x,y*TS-cam.y,(x+y)%2?(f%2?'#172a39':'#2b2138'):(f%2?'#1b3242':'#332743'));for(let i=0;i<25;i++){ctx.fillStyle=i%3?'#466d68':'#805b86';ctx.fillRect((i*79)%760-cam.x,(i*113)%650-cam.y,8,18)}}
function player(){let x=S.x*TS-cam.x,y=S.y*TS-cam.y,b=Math.sin(performance.now()/120)*.7;ctx.fillStyle='#0005';ctx.fillRect(x+4,y+21,16,4);ctx.fillStyle='#1d405c';ctx.fillRect(x+5,y+8+b,14,13);ctx.fillStyle='#2d5877';ctx.fillRect(x+6,y+10+b,12,4);ctx.fillStyle='#26333a';ctx.fillRect(x+4,y+20+b,6,4);ctx.fillRect(x+14,y+20+b,6,4);ctx.fillStyle='#e5bd91';ctx.fillRect(x+7,y+1+b,10,9);ctx.fillStyle='#b33e38';ctx.fillRect(x+5,y+b,14,4);ctx.fillStyle='#f2d77d';ctx.fillRect(x+16,y+2+b,4,2)}
function boat(){let x=S.x*TS-cam.x,y=S.y*TS-cam.y,b=Math.sin(performance.now()/300)*1.2;ctx.fillStyle='#0004';ctx.fillRect(x-2,y+19,28,5);ctx.fillStyle='#5e3d2c';ctx.fillRect(x+1,y+9+b,22,10);ctx.fillStyle='#a16946';ctx.fillRect(x+4,y+6+b,16,6);ctx.fillStyle='#e7dfc6';ctx.fillRect(x+10,y-5+b,3,12);ctx.fillRect(x+13,y-3+b,9,7);ctx.fillStyle='#2d596a';ctx.fillRect(x+15,y-1+b,4,3)}
let fishGame={phase:'idle',fish:null,wait:0,distance:1,tension:.3,fishDir:1,fishPos:.55,fishSpeed:.3,reel:false,hookWindow:0};
function zone(){if(S.map==='island')return 0;if(S.map==='sea')return Math.min(4,Math.max(1,S.boat));return Math.min(6,4+Math.floor(+S.map.split('-')[1]/3))}
function pickFish(){let z=zone(),pool=FISH.filter(f=>f.zone<=z&&f.zone>=Math.max(0,z-1));return pool[Math.floor(Math.random()*pool.length)]}
function startFishing(){if(S.bag.length>=S.bagCap)return toast('Pack full. Sell your catch.');fishGame={phase:'waiting',fish:pickFish(),wait:.8+Math.random()*1.5,distance:1,tension:.28,fishDir:Math.random()>.5?1:-1,fishPos:.55,fishSpeed:.25,reel:false,hookWindow:0};fishing=true;bite=0;toast('Line cast...')}
function hookFish(){if(fishGame.phase!=='bite')return;fishGame.phase='fight';fishGame.distance=.95;fishGame.tension=.36;fishGame.fishSpeed=.25+fishGame.fish.zone*.06;toast('HOOKED! Hold A to reel.');try{navigator.vibrate?.([30,20,30])}catch(e){}}
function finishCatch(){let f=fishGame.fish;S.bag.push(f);S.caught++;if(S.quest===0&&S.caught>=3)S.quest=1;fishing=false;bite=0;fishGame.phase='idle';toast(`Caught ${f.name} · $${f.value}`);try{navigator.vibrate?.(45)}catch(e){};hud()}
function loseFish(msg){fishing=false;bite=0;fishGame.phase='idle';fishGame.reel=false;toast(msg)}
function updateFishing(dt){if(!fishing)return;if(fishGame.phase==='waiting'){fishGame.wait-=dt;if(fishGame.wait<=0){fishGame.phase='bite';fishGame.hookWindow=1.15;bite=1;toast('BITE! Tap A!');try{navigator.vibrate?.(25)}catch(e){}}return}if(fishGame.phase==='bite'){fishGame.hookWindow-=dt;if(fishGame.hookWindow<=0)loseFish('Too slow — fish escaped.');return}if(fishGame.phase!=='fight')return;let f=fishGame.fish,rod=Math.max(0,S.rod||0),strength=.55+f.zone*.14+Math.min(1.1,f.value/1800);fishGame.fishPos+=fishGame.fishDir*fishGame.fishSpeed*dt;if(fishGame.fishPos<.15||fishGame.fishPos>.85)fishGame.fishDir*=-1;if(Math.random()<dt*(1+f.zone*.18))fishGame.fishDir*=-1;let pull=(Math.abs(fishGame.fishPos-.5)*.7+.2)*strength;if(fishGame.reel){fishGame.distance-=dt*(.20+rod*.035);fishGame.tension+=dt*(.34+pull*.35-Math.min(.12,rod*.018))}else{fishGame.distance+=dt*(.035+pull*.025);fishGame.tension-=dt*(.30+rod*.012)}fishGame.tension+=dt*(pull*.08-.035);fishGame.tension=Math.max(.05,fishGame.tension);fishGame.distance=Math.max(0,fishGame.distance);if(fishGame.tension>1.02)return loseFish('SNAP! The line broke.');if(fishGame.distance>1.12)return loseFish('The fish got away.');if(fishGame.distance<=.02)finishCatch()}
function drawFishFight(){if(!fishing)return;let y=H*.54;ctx.fillStyle='#071018dd';ctx.fillRect(14,H*.30,W-28,H*.40);ctx.strokeStyle='#d9e5d8';ctx.lineWidth=3;ctx.strokeRect(14,H*.30,W-28,H*.40);if(fishGame.phase==='waiting'){pixText('WAIT FOR A BITE...',W/2-68,y,'#ffe27b',13);return}if(fishGame.phase==='bite'){pixText('! BITE !',W/2-34,y-15,'#ffe27b',16);pixText('TAP A NOW',W/2-42,y+13,'#fff',12);return}let f=fishGame.fish;pixText(f.name.toUpperCase(),28,H*.34,'#ffe27b',12);pixText(`ROD T${S.rod||0}`,W-92,H*.34,'#9ed7e3',11);let bx=32,bw=W-64;pixText('LINE TENSION',bx,H*.40,'#fff',10);ctx.fillStyle='#26353e';ctx.fillRect(bx,H*.42,bw,16);ctx.fillStyle=fishGame.tension<.68?'#6dbd72':fishGame.tension<.88?'#e4c95d':'#d96053';ctx.fillRect(bx,H*.42,bw*Math.min(1,fishGame.tension),16);ctx.strokeStyle='#e8efdf';ctx.strokeRect(bx,H*.42,bw,16);pixText('DISTANCE',bx,H*.49,'#fff',10);ctx.fillStyle='#26353e';ctx.fillRect(bx,H*.51,bw,13);ctx.fillStyle='#6aa5cb';ctx.fillRect(bx,H*.51,bw*Math.min(1,fishGame.distance),13);ctx.strokeStyle='#e8efdf';ctx.strokeRect(bx,H*.51,bw,13);let trackY=H*.60;ctx.fillStyle='#16364a';ctx.fillRect(bx,trackY,bw,28);let fx=bx+bw*fishGame.fishPos;ctx.fillStyle='#d8e9df';ctx.fillRect(fx-12,trackY+9,18,8);ctx.fillRect(fx+6,trackY+6,5,14);ctx.fillStyle='#071018';ctx.fillRect(fx-7,trackY+11,2,2);pixText(fishGame.reel?'REELING...':'RELEASE TO LOWER TENSION',bx,H*.68,fishGame.reel?'#ffe27b':'#b9d8df',10)}
function render(){cam.x=Math.max(0,Math.min(MAPW*TS-W,S.x*TS-W/2));cam.y=Math.max(0,Math.min(MAPH*TS-H,S.y*TS-H/2));ctx.fillStyle='#08131a';ctx.fillRect(0,0,W,H);if(S.map==='island')drawIsland();else if(S.map==='sea')drawSea();else drawAbyss();S.map==='sea'?boat():player();drawFishFight()}
function action(){if(fishing){if(fishGame.phase==='bite')hookFish();return}if(S.map==='island'){if(Math.hypot(S.x-15,S.y-13)<2)return seller();if(Math.hypot(S.x-9,S.y-11)<3)return store();if(Math.hypot(S.x-23,S.y-11)<3)return workshop();if(S.y>21&&S.x>11&&S.x<21){if(!S.owned.includes('Boat Key'))return toast('The boat is locked.');S.map='sea';S.x=16;S.y=22;S.fuel=S.fuelMax||60;S.boat=Math.max(1,S.boat);S.quest=Math.max(3,S.quest);hud();return}return startFishing()}if(S.map==='sea'){if(S.y>25){S.map='island';S.x=16;S.y=21;hud();return}if(S.sub&&S.x<5&&S.y<5){S.map='abyss-1';S.x=16;S.y=22;S.quest=6;hud();return}return startFishing()}startFishing()}
function seller(){let total=S.bag.reduce((a,f)=>a+f.value,0),h=`<h2>SILAS — FISH BUYER</h2><p>“Bring me anything that swims, crawls or should probably have stayed down there.”</p><p>Your catch: <b>${S.bag.length}</b><br>Offer: <b>$${total}</b></p><button onclick="sellAll()">SELL EVERYTHING</button>`;if(!S.store)h+=`<p>The old General Store can reopen if someone funds the repairs.</p><button onclick="donate()">DONATE $500</button>`;modal(h)}
function sellAll(){let total=S.bag.reduce((a,f)=>a+f.value,0);S.money+=total;S.bag=[];closeM();toast('Sold catch for $'+total);hud()}
function donate(){if(S.money<500)return toast('Need $500.');S.money-=500;S.store=true;S.quest=Math.max(2,S.quest);closeM();toast('GENERAL STORE UNLOCKED!');hud()}
function store(){if(!S.store)return modal('<h2>GENERAL STORE — UNDER CONSTRUCTION</h2><p>A faded sign reads: REPAIRS NEEDED — $500.</p>');shop('GENERAL STORE',ITEMS.filter(i=>['rod','knife','bag','key','fuel','trap','tool','consumable','charm','map'].includes(i.type)&&i.tier<=Math.max(2,S.boat+1)))}
function workshop(){if(!S.workshop){if(S.money>=1800)return modal('<h2>OLD WORKSHOP</h2><p>The shipwright could reopen this place for $1,800.</p><button onclick="openWorkshop()">FUND WORKSHOP $1800</button>');return modal('<h2>OLD WORKSHOP</h2><p>Locked. Reopening cost: $1,800.</p>')}shop('HARBOR WORKSHOP',ITEMS.filter(i=>['boat','engine','sonar','sub','weapon'].includes(i.type)))}
function openWorkshop(){S.money-=1800;S.workshop=true;closeM();toast('WORKSHOP UNLOCKED');hud()}
function shop(title,list){let h='<h2>'+title+'</h2><div class="grid">';for(let i of list){let own=S.owned.includes(i.name);h+=`<div class="item"><b>${i.name}</b>${i.type.toUpperCase()} · T${i.tier}<br>$${i.price}<button ${own?'disabled':''} onclick='buy(${JSON.stringify(i.name)})'>${own?'OWNED':'BUY'}</button></div>`}modal(h+'</div>')}
function buy(name){let i=ITEMS.find(x=>x.name===name);if(S.money<i.price)return toast('Not enough money.');S.money-=i.price;S.owned.push(name);if(i.type==='bag')S.bagCap+=6;if(i.type==='rod')S.rod=Math.max(S.rod,i.tier);if(i.type==='knife')S.knife=Math.max(S.knife,i.tier);if(i.type==='weapon')S.weapon=Math.max(S.weapon,i.tier);if(i.name==='Boat Key'){S.fuelMax=60;S.quest=Math.max(3,S.quest)}if(i.type==='boat'){S.boat=Math.max(S.boat,i.tier);S.fuelMax=60+i.tier*45;S.quest=Math.max(4,S.quest)}if(i.name==='Mini Submarine'){S.sub=true;S.quest=5}if(i.type==='fuel')S.fuel=Math.min(S.fuelMax,S.fuel+(i.name==='Fuel Can'?35:80));closeM();hud();toast('Bought '+name)}
function inventory(){let a=S.owned.map(n=>`<div class="item"><b>${n}</b></div>`).join(''),b=S.bag.map(f=>`<div class="item"><b>${f.name}</b>$${f.value}</div>`).join('');modal(`<h2>PACK</h2><p>Gear ${S.owned.length}/${ITEMS.length}</p><div class="grid">${a}</div><p>Catch</p><div class="grid">${b||'<div class="item">Empty</div>'}</div>`)}
function modal(h){modalEl.innerHTML=h+'<button class="close" onclick="closeM()">CLOSE</button>';mw.style.display='flex'}
function closeM(){mw.style.display='none'}
function moveStep(dx,dy,dt){if(fishing||mw.style.display==='flex')return;let sp=4.1*dt,nx=S.x+dx*sp,ny=S.y+dy*sp;if(S.map==='sea'){if(S.fuel<=0)return;S.fuel=Math.max(0,S.fuel-dt*.7);S.x=Math.max(.5,Math.min(MAPW-1.5,nx));S.y=Math.max(.5,Math.min(MAPH-1.5,ny))}else if(!solid(Math.floor(nx),Math.floor(ny))){S.x=nx;S.y=ny}}
const joy=$('#joy'),knob=$('#joyKnob'),act=$('#act'),inv=$('#inv'),mw=$('#mw'),modalEl=$('#modal');let joyId=null,joyVec={x:0,y:0};function joyMove(e){let r=joy.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,l=Math.hypot(dx,dy),m=42;if(l>m){dx*=m/l;dy*=m/l}joyVec={x:dx/m,y:dy/m};knob.style.transform=`translate(${dx}px,${dy}px)`}joy.addEventListener('pointerdown',e=>{e.preventDefault();joyId=e.pointerId;joy.setPointerCapture?.(joyId);joyMove(e)});joy.addEventListener('pointermove',e=>{if(e.pointerId===joyId){e.preventDefault();joyMove(e)}});function joyEnd(e){if(joyId===null||e.pointerId!==joyId)return;joyId=null;joyVec={x:0,y:0};knob.style.transform='translate(0,0)'}joy.addEventListener('pointerup',joyEnd);joy.addEventListener('pointercancel',joyEnd);
act.addEventListener('pointerdown',e=>{e.preventDefault();if(fishing&&fishGame.phase==='fight'){fishGame.reel=true;return}action()});act.addEventListener('pointerup',e=>{e.preventDefault();fishGame.reel=false});act.addEventListener('pointercancel',()=>fishGame.reel=false);inv.addEventListener('pointerdown',e=>{e.preventDefault();if(!fishing)inventory()});
document.addEventListener('contextmenu',e=>e.preventDefault());document.addEventListener('selectstart',e=>e.preventDefault());
$('#go').addEventListener('pointerdown',e=>{e.preventDefault();$('#start').style.display='none';hud();last=performance.now();requestAnimationFrame(loop)});
function loop(t){let dt=Math.min(.033,(t-last)/1000||0);last=t;if(joyId!==null)moveStep(joyVec.x,joyVec.y,dt);updateFishing(dt);hud();render();requestAnimationFrame(loop)}
resize();hud();