function winBattle(){let f=battle.fish;P.bag.push(f);P.caught++;P.seen[f.name]=(P.seen[f.name]||0)+1;xp(20+f.zone*12);if(P.quest===1&&P.caught>=3)P.quest=2;E("battleMessage").textContent="SECURED! "+f.name+" · ₡"+f.value;hud();save();setTimeout(endBattle,850)}function loseBattle(){P.hp=P.hpMax;P.map="island";P.x=25;P.y=20;P.money=Math.max(0,P.money-50);E("battleMessage").textContent="WASHED ASHORE...";setTimeout(endBattle,900);save()}
function endBattle(){battle=null;E("battle").classList.add("hidden");E("worldButtons").classList.remove("hidden");E("joystick").classList.remove("hidden");hud()}
function drawPortraits(){if(!battle)return;let y=E("playerPortrait").getContext("2d"),f=E("enemyPortrait").getContext("2d"),t=performance.now(),b=Math.sin(t/360)*2;y.clearRect(0,0,160,160);f.clearRect(0,0,160,160);y.fillStyle="#1f4a6c";y.fillRect(25,86+b,105,50);y.fillStyle="#dfb38a";y.fillRect(45,32+b,70,57);y.fillStyle="#7a4931";y.fillRect(34,21+b,92,19);y.fillStyle="#fff";y.fillRect(61,58+b,8,8);y.fillRect(91,58+b,8,8);y.fillStyle="#222";y.fillRect(64,61+b,3,4);y.fillRect(94,61+b,3,4);let m=Math.sin(t/280)*3,typ=battle.fish.type,col=typ==="crab"?"#d87762":typ==="jelly"?"#b77dd0":typ==="shark"?"#59798c":typ==="eel"?"#74a05f":typ==="cephalopod"?"#a56d8d":"#65b5c7";f.fillStyle=col;f.fillRect(35+m,58,90,55);f.fillStyle="#fff";f.fillRect(55+m,74,8,8);f.fillRect(96+m,74,8,8);f.fillStyle="#111";f.fillRect(58+m,77,3,3);f.fillRect(99+m,77,3,3)}
function portraitCSS(name){let n=NPCS[name],e=E("dialoguePortrait");e.innerHTML="";e.style.background=`linear-gradient(160deg,${n.shirt},#10222e)`;let h=document.createElement("div");h.style.cssText=`position:absolute;left:24%;top:18%;width:52%;height:45%;border-radius:45% 45% 38% 38%;background:${n.skin};box-shadow:0 -13px 0 ${n.hair}`;e.appendChild(h)}
function talk(name){let n=NPCS[name],line=choice(n.lines);portraitCSS(name);E("dialogueName").textContent=name.toUpperCase()+" — "+n.role.toUpperCase();E("dialogueText").textContent=line;let c=E("dialogueChoices");c.innerHTML="";const add=(t,fn)=>{let b=document.createElement("button");b.textContent=t;b.onclick=fn;c.appendChild(b)};if(name==="Fritz"){add("Sell Catch",()=>{closeDialogue();seller()});add("Gear",()=>{closeDialogue();shop("FRITZ'S GEAR",ITEMS.filter(i=>["knife","weapon","bag","fuel","consumable","gift"].includes(i.type)&&i.tier<=Math.max(2,P.level/3+1)))})}if(name==="Luna")add("Tackle Shop",()=>{closeDialogue();shop("LUNA'S TACKLE",ITEMS.filter(i=>["rod","bait","trap","charm","tool"].includes(i.type)&&i.tier<=Math.max(2,P.level/2+1)))});if(name==="Nico")add("Shipyard",()=>{closeDialogue();shipyard()});if(name==="Maris")add("Research",()=>{closeDialogue();research()});if(name==="Biscuit")add("Give Treat",()=>gift(name,"Biscuit Treats"));if(name==="Skipper")add("Offer Sardines",()=>gift(name,"Skipper Sardines"));add("Later",closeDialogue);E("dialogue").classList.remove("hidden");P.relationships[name]=(P.relationships[name]||0)+1;if(P.quest===0&&name==="Fritz")P.quest=1;hud();save()}
function closeDialogue(){E("dialogue").classList.add("hidden")}
function gift(name,item){if(!P.owned.includes(item))return toast("You don't have that gift.");P.relationships[name]+=3;toast(name+" likes you more.");closeDialogue();save()}
function seller(){let total=P.bag.reduce((a,f)=>a+f.value,0),h=`<h2>FRITZ — FISH BUYER</h2><p>“Bring me anything that swims, crawls, glows, or looks offended to be up here.”</p><p>Catches: <b>${P.bag.length}</b> · Offer: <b>₡${total}</b></p><button onclick="sellAll()">SELL EVERYTHING</button>`;if(P.quest===2&&!P.store)h+=`<h3>Rebuild the harbor</h3><p>Luna can reopen her tackle shop for ₡150.</p><button onclick="reopenLuna()">FUND LUNA'S SHOP · ₡150</button>`;modal(h)}
window.sellAll=function(){let total=P.bag.reduce((a,f)=>a+f.value,0);P.money+=total;P.bag=[];if(P.quest===2&&P.money>=150){}closeModal();hud();save()};window.reopenLuna=function(){if(P.money<150)return toast("Need ₡150.");P.money-=150;P.store=true;P.quest=3;closeModal();toast("LUNA'S TACKLE REOPENED");hud();save()};
function shop(title,list){let h=`<h2>${title}</h2><div class="grid">`;for(const i of list){let own=P.owned.includes(i.name)&&!['fuel','consumable','gift'].includes(i.type);h+=`<div class="item"><b>${i.name}</b><small>${i.type.toUpperCase()} · T${i.tier}</small>${i.desc}<br><b>₡${i.price}</b><button ${own?'disabled':''} onclick='buyItem(${JSON.stringify(i.name)})'>${own?'OWNED':'BUY'}</button></div>`}h+="</div>";modal(h)}
