["Harbor Sardine",8,"fish",30,0,"common"],["Silver Herring",12,"fish",34,0,"common"],["Rock Goby",16,"fish",38,0,"common"],["Green Crab",22,"crab",48,0,"uncommon"],["Sand Shrimp",25,"crab",44,0,"uncommon"],["Blue Mackerel",28,"fish",50,1,"common"],["Needlefish",36,"fish",56,1,"uncommon"],["Red Reef Crab",44,"crab",62,1,"uncommon"],["Moon Jelly",52,"jelly",54,1,"rare"],["Striped Bass",62,"fish",72,2,"uncommon"],["Sea Bream",70,"fish",76,2,"uncommon"],["Spiny Lobster",88,"crab",90,2,"rare"],["Glass Squid",110,"cephalopod",96,2,"rare"],["Bluefin Warden",165,"fish",120,3,"epic"],["Reef Shark",190,"shark",135,3,"epic"],["Giant Octopus",220,"cephalopod",150,3,"epic"],["Storm Eel",250,"eel",145,3,"epic"],["Black Marlin",310,"fish",165,4,"epic"],["Sawtooth Shark",360,"shark",180,4,"legendary"],["Ghost Manta",420,"fish",175,4,"legendary"],["Abyss Lantern",520,"fish",190,5,"rare"],["Violet Fang Eel",610,"eel",205,5,"epic"],["Crown Jelly",700,"jelly",220,5,"epic"],["Ironclaw Crab",820,"crab",240,5,"legendary"],["Cathedral Squid",1100,"cephalopod",280,6,"legendary"],["Pale Leviathan",1600,"fish",360,6,"mythic"],["Trench Warden",2100,"shark",420,7,"mythic"],["The Bell Below",3000,"jelly",500,8,"mythic"]
].map(([name,value,type,hp,zone,rarity])=>({name,value,type,hp,zone,rarity}));
const NPCS={
Fritz:{x:26,y:18,shirt:"#d0a14d",hair:"#6b4935",skin:"#e3bd91",role:"Harbor Master",trait:"warm, cryptic, protective",lines:["The sea missed you, kid. I could tell by how badly it behaved.","A good harbor isn't wood and rope. It's people who come back.","Don't rush deep water. The ocean charges interest."],shop:"buyer"},
Luna:{x:11,y:21,shirt:"#5c8d89",hair:"#302c34",skin:"#dfad86",role:"Tackle Maker",trait:"confident, practical, inventive",lines:["A fancy rod won't save bad timing. But it helps.","Bring me better materials and I'll make your gear sing.","Fritz pretends he taught me everything. Cute, isn't it?"],shop:"tackle"},
Nico:{x:40,y:15,shirt:"#53728f",hair:"#d5b26a",skin:"#d9ad86",role:"Shipwright",trait:"energetic, fearless, mechanically gifted",lines:["If it floats, I can make it faster. If it doesn't, give me an hour.","Fuel is freedom. Hull strength is coming home.","One day we're building something that goes down, not out."],shop:"shipyard"},
Maris:{x:16,y:12,shirt:"#985f7d",hair:"#423443",skin:"#e4b78e",role:"Explorer",trait:"brilliant, curious, obsessed with the unknown",lines:["Every species is a clue. The deep ones are a language.","My instruments say there are structures below the trench.","Bring me strange catches before Fritz turns them into dinner."],shop:"research"},
Biscuit:{x:27,y:20,shirt:"#c9934b",hair:"#9a6c39",skin:"#d9ab61",role:"Fritz's First Mate",trait:"loyal, excitable, lucky",lines:["Biscuit spins in a circle and drops a wet rope at your feet.","Biscuit sniffs your pack. Very professionally.","Biscuit barks at the sea. The sea does not answer."],shop:"companion"},
Skipper:{x:34,y:21,shirt:"#d7d4c8",hair:"#6c7076",skin:"#d6b06d",role:"Harbor Watch",trait:"grumpy, territorial, secretly helpful",lines:["Skipper stares at you like you owe him money.","Skipper pecks the sign marked NO FISH CLEANING HERE.","Skipper reluctantly approves of your seamanship."],shop:"watch"}
};
const BUILDINGS=[[7,7,8,5,"LUNA'S TACKLE","#387784"],[36,8,9,5,"NICO'S SHIPYARD","#5d6878"],[20,8,8,5,"MARIS LAB","#72587b"],[21,16,10,5,"FRITZ'S","#9f5b3e"],[5,25,7,4,"YOUR ROOM","#70513c"],[40,24,7,5,"LIGHTHOUSE","#5a5050"]];
const LAND=Array.from({length:MH},()=>Array(MW).fill(false));function fill(x1,y1,x2,y2){for(let y=y1;y<=y2;y++)for(let x=x1;x<=x2;x++)if(x>=0&&y>=0&&x<MW&&y<MH)LAND[y][x]=true}fill(5,4,48,7);fill(3,8,50,15);fill(2,16,51,22);fill(4,23,49,27);fill(8,28,45,31);fill(14,32,39,33);for(let y=20;y<=27;y++)for(let x=23;x<=32;x++)LAND[y][x]=false;for(let y=22;y<=34;y++){LAND[y][19]=LAND[y][20]=LAND[y][37]=LAND[y][38]=true}for(let x=19;x<=25;x++)LAND[34][x]=true;for(let x=32;x<=38;x++)LAND[34][x]=true;
function resize(){D=Math.min(2,devicePixelRatio||1);W=innerWidth;H=innerHeight;C.width=W*D;C.height=H*D;X.setTransform(D,0,0,D,0,0)}addEventListener("resize",resize);
function px(x,y,w,h,c){X.fillStyle=c;X.fillRect(Math.round(x),Math.round(y),w,h)}function txt(t,x,y,c="#fff",z=11){X.font="900 "+z+"px monospace";X.fillStyle="#061018";X.fillText(t,x+1,y+1);X.fillStyle=c;X.fillText(t,x,y)}function hash(a,b,m){return Math.abs(((a*73856093)^(b*19349663))%m)}
function isLand(x,y){let tx=Math.floor(x),ty=Math.floor(y);return tx>=0&&ty>=0&&tx<MW&&ty<MH&&LAND[ty][tx]}function blocked(x,y){if(P.map!=="island")return false;let r=.3;for(const q of [[x-r,y-r],[x+r,y-r],[x-r,y+r],[x+r,y+r]])if(!isLand(q[0],q[1]))return true;for(const b of BUILDINGS)if(x+r>b[0]&&x-r<b[0]+b[2]&&y+r>b[1]&&y-r<b[1]+b[3])return true;return false}function waterAhead(){return P.map!=="island"||!isLand(P.x+face.x*.8,P.y+face.y*.8)}
