function save(){localStorage.setItem(saveKey,JSON.stringify(P))}function load(){let s=localStorage.getItem(saveKey);if(!s)return false;Object.assign(P,JSON.parse(s));return true}
function xp(n){P.xp+=n;while(P.xp>=P.level*100){P.xp-=P.level*100;P.level++;P.hpMax+=8;P.hp=P.hpMax;toast("LEVEL UP — "+P.level)}hud()}
function zone(){if(P.map==="island")return 0;if(P.map==="sea")return Math.min(4,Math.max(1,P.boat));return Math.min(8,4+Math.floor(+P.map.split("-")[1]/2))}
function pickFish(){let z=zone(),pool=FISH.filter(f=>f.zone<=z&&f.zone>=Math.max(0,z-1));let rare=P.owned.includes("Lucky Scale")&&Math.random()<.18?pool.filter(f=>["rare","epic","legendary","mythic"].includes(f.rarity)):[];return choice(rare.length?rare:pool)}
function startFishing(){if(P.bag.length>=P.bagCap)return toast("Pack full. Sell your catch.");if(!waterAhead())return toast("Face the water.");fishing={phase:"waiting",fish:pickFish(),wait:rnd(.65,P.owned.includes("Bait Box")?1.2:1.8),distance:1,tension:.26,reel:false};E("fishingUI").classList.remove("hidden");E("fishName").textContent="CASTING";E("fishMessage").textContent="Wait for a bite..."}
function hook(){fishing.phase="fight";E("fishName").textContent=fishing.fish.name.toUpperCase()+" · "+fishing.fish.rarity.toUpperCase();E("fishMessage").textContent="HOOKED — HOLD ACTION TO REEL"}
function updateFishing(dt){if(fishing.phase==="idle")return;if(fishing.phase==="waiting"){fishing.wait-=dt;if(fishing.wait<=0){fishing.phase="bite";fishing.wait=1.15;E("fishMessage").textContent="BITE! TAP ACTION"}}else if(fishing.phase==="bite"){fishing.wait-=dt;if(fishing.wait<=0){fishing={phase:"idle"};E("fishingUI").classList.add("hidden");toast("Too slow.")}}else if(fishing.phase==="fight"){let z=fishing.fish.zone,rod=P.rod,assist=P.owned.includes("Quick-Reel Module")?.05:0;if(fishing.reel){fishing.distance-=dt*(.17+rod*.035+assist);fishing.tension+=dt*(.26+z*.025)}else{fishing.distance+=dt*(.026+z*.006);fishing.tension-=dt*(.28+rod*.012)}fishing.tension=clamp(fishing.tension,.04,1.25);let snap=P.owned.includes("Reinforced Line")?1.12:P.owned.includes("Blackglass Line")?1.2:1.02;E("tensionFill").style.width=Math.min(100,fishing.tension/snap*100)+"%";E("distanceFill").style.width=Math.min(100,fishing.distance*100)+"%";E("tensionFill").style.background=fishing.tension>snap*.84?"#d85f53":"#6fbd72";if(fishing.tension>snap){fishing={phase:"idle"};E("fishingUI").classList.add("hidden");toast("SNAP! Line broke.")}else if(fishing.distance>1.15){fishing={phase:"idle"};E("fishingUI").classList.add("hidden");toast("It escaped.")}else if(fishing.distance<=.02){let f=fishing.fish;fishing={phase:"idle"};E("fishingUI").classList.add("hidden");beginBattle(f)}}}
function battleMoves(){let a=[{name:"GRAB",power:9},{name:"KNIFE",power:7+P.knife*7,req:"knife"},{name:"HARPOON",power:10+P.weapon*10,req:"weapon"},{name:"FOCUS STRIKE",power:26+P.level*2,focus:40}];return a.filter(m=>!m.req||(m.req==="knife"?P.knife>0:P.weapon>0))}
function beginBattle(f){battle={fish:f,hp:f.hp,max:f.hp};E("battle").classList.remove("hidden");E("worldButtons").classList.add("hidden");E("joystick").classList.add("hidden");E("enemyName").textContent=f.name.toUpperCase();renderMoves();battleUI();E("battleMessage").textContent="YOUR TURN"}
function renderMoves(){E("moves").innerHTML="";for(const m of battleMoves()){let b=document.createElement("button");b.className="moveBtn";b.innerHTML="<strong>"+m.name+"</strong><small>"+(m.focus?m.focus+" Focus":"Timing attack")+"</small>";b.onclick=()=>attack(m);E("moves").appendChild(b)}}
function attack(m){if(timing)return;if(m.focus&&P.focus<m.focus)return toast("Need more Focus.");if(m.focus)P.focus-=m.focus;timing={mode:"attack",move:m,pos:0,dir:1,speed:1.45+battle.fish.zone*.05};E("timingBar").classList.remove("hidden");E("timingButton").classList.add("pulse")}
function enemy(){timing={mode:"defense",pos:0,dir:1,speed:1.65+battle.fish.zone*.07};E("timingBar").classList.remove("hidden");E("timingButton").classList.add("pulse");E("battleMessage").textContent="PARRY!"}
function resolveTiming(){if(!timing)return;let q=Math.abs(timing.pos-.5),perfect=q<.045,good=q<.16,t=timing;timing=null;E("timingBar").classList.add("hidden");E("timingButton").classList.remove("pulse");if(t.mode==="attack"){let d=perfect?Math.round(t.move.power*2.15):good?Math.round(t.move.power*1.25):Math.max(1,Math.round(t.move.power*.4));battle.hp-=d;P.focus=clamp(P.focus+(perfect?18:good?9:4),0,100);E("battleMessage").textContent=(perfect?"CRITICAL PERFECT! ":"")+d+" DAMAGE";battleUI();if(battle.hp<=0)return winBattle();setTimeout(enemy,520)}else{let base=8+battle.fish.zone*3,d=perfect?0:good?Math.round(base*.35):base;P.hp-=d;E("battleMessage").textContent=perfect?"PERFECT PARRY!":"HIT −"+d;battleUI();if(P.hp<=0)return loseBattle();setTimeout(()=>E("battleMessage").textContent="YOUR TURN",520)}}
function battleUI(){E("playerHp").textContent=Math.max(0,P.hp);E("playerHpFill").style.width=100*P.hp/P.hpMax+"%";E("focus").textContent=P.focus;E("enemyHp").textContent=Math.max(0,Math.round(battle.hp));E("enemyHpMax").textContent=battle.max;E("enemyHpFill").style.width=100*Math.max(0,battle.hp)/battle.max+"%"}
