(()=>{"use strict";
const E=id=>document.getElementById(id),C=E("game"),X=C.getContext("2d"),MC=E("mini"),MX=MC.getContext("2d");
const TS=32,MW=54,MH=38,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rnd=(a,b)=>a+Math.random()*(b-a),choice=a=>a[Math.floor(Math.random()*a.length)];
let W=0,H=0,D=1,last=0,cam={x:0,y:0},face={x:0,y:1},clock=8,weather="SUN";
const saveKey="tidebound-fischers-fritz-v1";
const P={name:"Kai",map:"island",x:25,y:20,money:0,bag:[],bagCap:10,caught:0,hp:100,hpMax:100,focus:0,xp:0,level:1,quest:0,owned:["Bamboo Rod"],rod:0,knife:0,weapon:0,boat:0,fuel:0,fuelMax:0,sub:false,store:false,workshop:false,relationships:{Fritz:0,Luna:0,Nico:0,Maris:0,Biscuit:0,Skipper:0},flags:{},seen:{}};
const J={on:false,id:null,x:0,y:0};let fishing={phase:"idle"},battle=null,timing=null;
const ITEMS=[
["Bamboo Rod","rod",0,0,"A simple first rod."],["Reed Rod","rod",90,1,"More forgiving tension."],["Oak Rod","rod",220,2,"Strong harbor rod."],["Carbon Rod","rod",520,3,"Fast reel response."],["Deepwater Rod","rod",980,4,"Built for offshore giants."],["Abyss Rod","rod",1900,5,"Pressure-rated blackglass rod."],
["Pocket Knife","knife",45,0,"Basic utility blade."],["Fillet Knife","knife",140,1,"Better creature handling."],["Sailor Knife","knife",300,2,"Reliable at sea."],["Titanium Knife","knife",700,3,"Corrosion-proof."],["Abyssal Blade","knife",1500,4,"Cuts deep-sea armor."],
["Rusty Harpoon","weapon",140,0,"Old but usable."],["Harpoon Gun","weapon",430,1,"Powerful ranged hit."],["Speargun","weapon",900,2,"Fast underwater weapon."],["Shock Spear","weapon",1700,3,"Stuns dangerous catches."],["Flare Pistol","weapon",320,1,"Bright emergency strike."],["Net Launcher","weapon",760,2,"Control larger creatures."],["Pressure Lance","weapon",2600,4,"Abyss expedition weapon."],
["Small Backpack","bag",100,1,"+6 pack capacity."],["Canvas Pack","bag",260,2,"+8 pack capacity."],["Deck Pack","bag",580,3,"+10 pack capacity."],["Expedition Pack","bag",1100,4,"+14 pack capacity."],
["Boat Key","key",650,1,"Unlocks Fritz's old skiff."],["Skiff Hull","boat",1200,1,"First seaworthy boat."],["Coastal Hull","boat",2800,2,"Reach outer islands."],["Offshore Hull","boat",5600,3,"Cross deep channels."],["Long-Range Hull","boat",9800,4,"Reach the edge of the chart."],["Outboard I","engine",850,1,"Improves range."],["Outboard II","engine",2100,2,"Fuel-efficient engine."],["Twin Outboard","engine",4800,3,"Fast offshore travel."],["Deep Sonar","sonar",3600,3,"Reveal rare fishing zones."],["Abyss Sonar","sonar",7200,4,"Finds descent points."],["Submersible Frame","sub",14500,5,"Unlocks the underwater world."],["Pressure Dome","sub",5200,5,"Deeper floor access."],["Ballast Upgrade","sub",7600,6,"Abyss floor extension."],
["Fuel Can","fuel",75,1,"+20 fuel."],["Large Fuel Drum","fuel",180,2,"+50 fuel."],["Repair Kit","consumable",120,1,"Repairs travel damage."],["Med Kit","consumable",90,1,"Restore HP."],["Bait Box","bait",55,1,"Improves bite rate."],["Glow Worm Bait","bait",170,2,"Attracts deepwater species."],["Crab Pot","trap",260,2,"Passive crustacean tool."],["Lobster Cage","trap",520,3,"Rare shellfish gear."],["Tidal Map","map",200,1,"Marks harbor currents."],["Outer Sea Chart","map",650,2,"Marks distant zones."],["Abyss Chart","map",2400,4,"Maps first descent floors."],["Compass Charm","charm",310,1,"Slight XP bonus."],["Lucky Scale","charm",520,2,"Better rare chance."],["Storm Pendant","charm",900,3,"Weather resistance."],["Pressure Amulet","charm",1800,4,"Abyss protection."],["Quick-Reel Module","tool",420,2,"Faster reeling."],["Auto-Balancer","tool",950,3,"Reduces tension spikes."],["Creature Scanner","tool",1800,3,"Shows catch details."],["Sample Case","tool",650,2,"Maris research equipment."],["Dock Lantern","tool",120,1,"Night harbor light."],["Diving Fins","tool",780,3,"Sub expedition mobility."],["Reinforced Line","tool",350,2,"Higher snap threshold."],["Blackglass Line","tool",2100,5,"Abyss line."],["Signal Beacon","tool",560,2,"Emergency travel marker."],["Weather Radio","tool",730,2,"Forecast storms."],["Biscuit Treats","gift",35,1,"Biscuit loves these."],["Skipper Sardines","gift",25,1,"Bribe the harbor watch."],["Old Sea Stories","gift",90,1,"Fritz appreciates them."],["Fine Thread","gift",85,1,"Luna can use this."],["Engine Grease","gift",95,1,"Useful to Nico."],["Field Notes","gift",120,1,"Maris collects research."]
].map(([name,type,price,tier,desc])=>({name,type,price,tier,desc}));
const FISH=[
