(()=>{"use strict";
const E=id=>document.getElementById(id),C=E("game"),X=C.getContext("2d"),MC=E("mini"),MX=MC.getContext("2d");
const TS=32,MW=54,MH=38,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rnd=(a,b)=>a+Math.random()*(b-a),choice=a=>a[Math.floor(Math.random()*a.length)];
let W=0,H=0,D=1,last=0,cam={x:0,y:0},face={x:0,y:1},clock=8,weather="SUN";
const saveKey="tidebound-fischers-fritz-v1";
const P={name:"Kai",map:"island",x:25,y:20,money:0,bag:[],bagCap:10,caught:0,hp:100,hpMax:100,focus:0,xp:0,level:1,quest:0,owned:["Bamboo Rod"],rod:0,knife:0,weapon:0,boat:0,fuel:0,fuelMax:0,sub:false,store:false,workshop:false,relationships:{Fritz:0,Luna:0,Nico:0,Maris:0,Biscuit:0,Skipper:0},flags:{},seen:{}};
const J={on:false,id:null,x:0,y:0};let fishing={phase:"idle"},battle=null,timing=null;
const ITEMS=[
["Bamboo Rod","rod",0,0,"A simple first rod."],["Reed Rod","rod",90,1,"More forgiving tension."],["Oak Rod","rod",220,2,"Strong harbor rod."],["Carbon Rod","rod",520,3,"Fast reel response."],["Deepwater Rod","rod",980,4,"Built for offshore giants."],["Abyss Rod","rod",1900,5,"Pressure-rated blackglass rod."],
["Pocket Knife","knife",45,0,"Basic utility blade."],["Fillet Knife","knife",140,1,"Better creature handling."],["Sailor Knife","knife",300,2,"Reliable at sea."],["Titanium Knife","knife",700,3,"Corrosion-proof."],["Abyssal Blade","knife",1500,4,"Cuts deep-sea armor."],
["Rusty Harpoon","weapon",140,0,"Old but usable."],["Harpoon Gun","weapon",430,1,"Powerful ranged hit."],["Speargun","weapon",900,2,"Fast underwater weapon."],["Shock Spear","weapon",1700,3,"Stuns dangerous catches."],["Flare Pistol","weapon",320,1,"Bright emergency strike."],["Net Launcher","weapon",760,2,"Control larger creatures."],["Pressure Lance","weapon",2600,4,"Abyss expedition weapon."],
["Small Backpack","bag",100,1,"+6 pack capacity."],["Canvas Pack","bag",260,2,"+8 pack capacity."],["Deck Pack","bag",580,3,"+10 pack capacity."],["Expedition Pack","bag",1100,4,"+14 pack capacity."],
["Boat Key","key",650,1,"Unlocks Fritz's old skiff."],["Skiff Hull","boat",1200,1,"First seaworthy boat."],["Coastal Hull","boat",2800,2,"Reach outer islands."],["Offshore Hull","boat",5600,3,"Cross deep channels."],["Long-Range Hull","boat",9800,4,"Reach the edge of the chart."],["Outboard I","engine",850,1,"Improves range."],["Outboard II","engine",2100,2,"Fuel-efficient engine."],["Twin Outboard","engine",4800,3,"Fast offshore travel."],["Deep Sonar","sonar",3600,3,"Reveal rare fishing zones."],["Abyss Sonar","sonar",7200,4,"Finds descent points."],["Submersible Frame","sub",14500,5,"Unlocks the underwater world."],["Pressure Dome","sub",5200,5,"Deeper floor access."],["Ballast Upgrade","sub",7600,6,"Abyss floor extension."],
["Fuel Can","fuel",75,1,"+20 fuel."],["Large Fuel Drum","fuel",180,2,"+50 fuel."],["Repair Kit","consumable",120,1,"Repairs travel damage."],["Med Kit","consumable",90,1,"Restore HP."],["Bait Box","bait",55,1,"Improves bite rate."],["Glow Worm Bait","bait",170,2,"Attracts deepwater species."],["Crab Pot","trap",260,2,"Passive crustacean tool."],["Lobster Cage","trap",520,3,"Rare shellfish gear."],["Tidal Map","map",200,1,"Marks harbor currents."],["Outer Sea Chart","map",650,2,"Marks distant zones."],["Abyss Chart","map",2400,4,"Maps first descent floors."],["Compass Charm","charm",310,1,"Slight XP bonus."],["Lucky Scale","charm",520,2,"Better rare chance."],["Storm Pendant","charm",900,3,"Weather resistance."],["Pressure Amulet","charm",1800,4,"Abyss protection."],["Quick-Reel Module","tool",420,2,"Faster reeling."],["Auto-Balancer","tool",950,3,"Reduces tension spikes."],["Creature Scanner","tool",1800,3,"Shows catch details."],["Sample Case","tool",650,2,"Maris research equipment."],["Dock Lantern","tool",120,1,"Night harbor light."],["Diving Fins","tool",780,3,"Sub expedition mobility."],["Reinforced Line","tool",350,2,"Higher snap threshold."],["Blackglass Line","tool",2100,5,"Abyss line."],["Signal Beacon","tool",560,2,"Emergency travel marker."],["Weather Radio","tool",730,2,"Forecast storms."],["Biscuit Treats","gift",35,1,"Biscuit loves these."],["Skipper Sardines","gift",25,1,"Bribe the harbor watch."],["Old Sea Stories","gift",90,1,"Fritz appreciates them."],["Fine Thread","gift",85,1,"Luna can use this."],["Engine Grease","gift",95,1,"Useful to Nico."],["Field Notes","gift",120,1,"Maris collects research."]
].map(([name,type,price,tier,desc])=>({name,type,price,tier,desc}));
const FISH=[
{name:"Harbor Sprat",zone:0,value:18,hp:18,atk:4,xp:8},{name:"Silver Mullet",zone:0,value:28,hp:24,atk:5,xp:10},{name:"Red Rock Crab",zone:0,value:35,hp:28,atk:6,xp:11},{name:"Blue Sardine",zone:0,value:22,hp:20,atk:4,xp:9},{name:"Golden Perch",zone:1,value:55,hp:38,atk:7,xp:16},{name:"Coastal Bass",zone:1,value:68,hp:44,atk:8,xp:18},{name:"Moon Jelly",zone:1,value:75,hp:42,atk:9,xp:20},{name:"Tiger Shrimp",zone:1,value:62,hp:40,atk:8,xp:18},{name:"Reef Snapper",zone:2,value:110,hp:58,atk:11,xp:28},{name:"Spiny Lobster",zone:2,value:145,hp:70,atk:12,xp:34},{name:"Glass Squid",zone:2,value:155,hp:66,atk:13,xp:36},{name:"Moray Eel",zone:2,value:170,hp:78,atk:15,xp:40},{name:"Bluefin Warden",zone:3,value:320,hp:110,atk:19,xp:58},{name:"Hammerhead",zone:3,value:360,hp:125,atk:21,xp:65},{name:"Giant Octopus",zone:3,value:390,hp:135,atk:22,xp:70},{name:"Storm Marlin",zone:4,value:620,hp:170,atk:26,xp:90},{name:"Black Reef Shark",zone:4,value:680,hp:185,atk:28,xp:98},{name:"Lantern Leviathan",zone:5,value:1100,hp:230,atk:34,xp:145},{name:"Abyss Crab",zone:5,value:920,hp:220,atk:32,xp:132},{name:"Void Eel",zone:6,value:1600,hp:300,atk:42,xp:210}
];
function resize(){D=Math.min(2,devicePixelRatio||1);W=innerWidth;H=innerHeight;C.width=W*D;C.height=H*D;C.style.width=W+"px";C.style.height=H+"px";X.setTransform(D,0,0,D,0,0)}addEventListener("resize",resize);
function save(){localStorage.setItem(saveKey,JSON.stringify(P))}function load(){try{Object.assign(P,JSON.parse(localStorage.getItem(saveKey)||"{}"))}catch{}}
function toast(t){E("toast").textContent=t;E("toast").classList.add("show");clearTimeout(toast._t);toast._t=setTimeout(()=>E("toast").classList.remove("show"),1800)}
function zone(){if(P.map==="island")return 0;if(P.map==="sea")return Math.min(4,Math.max(1,P.boat));let n=+P.map.split("-")[1]||1;return Math.min(6,4+Math.floor(n/2))}
function fishPool(){let z=zone(),p=FISH.filter(f=>f.zone<=z&&f.zone>=Math.max(0,z-1));return p.length?p:FISH.slice(0,4)}
function hud(){E("money").textContent=Math.floor(P.money);E("level").textContent=P.level;E("xp").textContent=P.xp;E("bag").textContent=P.bag.length;E("bagCap").textContent=P.bagCap;E("area").textContent=P.map==="island"?"FRITZ HARBOR":P.map==="sea"?"OPEN SEA":P.map.toUpperCase();E("fuelStat").classList.toggle("hidden",P.map!=="sea");E("fuel").textContent=Math.ceil(P.fuel);E("fuelMax").textContent=P.fuelMax;let q=["Talk to Fritz.","Catch 3 creatures and sell them to Fritz.","Reopen Luna's tackle shop.","Buy the Boat Key.","Launch the skiff and explore the sea.","Upgrade your boat and find Maris.","Build the submersible.","Descend into the Abyss."];E("quest").textContent=q[Math.min(P.quest,q.length-1)]}
function blocked(x,y){if(P.map!=="island")return false;if(x<2||y<2||x>MW-3||y>MH-3)return true;let water=y>31;return water&&!(x>23&&x<31)}
function waterAhead(){let tx=P.x+face.x*1.2,ty=P.y+face.y*1.2;if(P.map==="island")return ty>30;return true}
function drawIsland(){X.fillStyle="#65c7d7";X.fillRect(0,0,W,H);let ox=-cam.x,oy=-cam.y;X.fillStyle="#d9c58d";X.fillRect(0+ox,0+oy,MW*TS,31*TS);X.fillStyle="#9a6a45";for(let x=23;x<31;x++)X.fillRect(x*TS+ox,30*TS+oy,TS,4*TS);for(let i=0;i<40;i++){let x=(i*137)% (MW*TS),y=(i*83)% (27*TS);X.fillStyle=i%3?"#4e9b63":"#6ba85a";X.fillRect(x+ox,y+oy,18,18)}drawBuilding(9,10,8,5,"FRITZ'S");drawBuilding(21,8,8,5,"LUNA");drawBuilding(35,10,9,6,"NICO");drawNPC(16,18,"Fritz","#6f8ea8");drawNPC(25,16,"Luna","#2f9a92");drawNPC(39,18,"Nico","#d59c44");drawNPC(30,22,"Maris","#7b6baa");drawNPC(18,21,"Biscuit","#c99a47");drawNPC(12,16,"Skipper","#ddd")}
function drawSea(){X.fillStyle=weather==="STORM"?"#31566a":"#167e9d";X.fillRect(0,0,W,H);for(let y=0;y<H;y+=26){X.fillStyle="rgba(255,255,255,.08)";X.fillRect((y*7+performance.now()/35)%(W+100)-100,y,W/3,2)}for(let i=0;i<12;i++){let x=((i*211)% (MW*TS))-cam.x,y=((i*137)% (MH*TS))-cam.y;X.fillStyle="#d9c58d";X.beginPath();X.arc(x,y,35+(i%3)*12,0,Math.PI*2);X.fill();X.fillStyle="#5a9a58";X.fillRect(x-8,y-12,16,24)}}
function drawAbyss(){let g=X.createLinearGradient(0,0,0,H);g.addColorStop(0,"#08202d");g.addColorStop(1,"#02070c");X.fillStyle=g;X.fillRect(0,0,W,H);for(let i=0;i<80;i++){let x=(i*97)%W,y=(i*173+performance.now()/40)%H;X.fillStyle="rgba(81,207,220,.22)";X.fillRect(x,y,2,2)}}
function drawBuilding(x,y,w,h,label){let sx=x*TS-cam.x,sy=y*TS-cam.y;X.fillStyle="#8a5a3c";X.fillRect(sx,sy,w*TS,h*TS);X.fillStyle="#d3b46c";X.fillRect(sx-5,sy-12,w*TS+10,15);X.fillStyle="#162331";X.font="bold 11px system-ui";X.fillText(label,sx+8,sy+24)}
function drawNPC(x,y,name,col){let sx=x*TS-cam.x,sy=y*TS-cam.y;X.fillStyle=col;X.fillRect(sx-8,sy-5,16,22);X.fillStyle="#e7c3a0";X.fillRect(sx-6,sy-13,12,10);X.fillStyle="#fff";X.font="10px system-ui";X.textAlign="center";X.fillText(name,sx,sy-18);X.textAlign="left"}
function drawPlayer(){let sx=P.x*TS-cam.x,sy=P.y*TS-cam.y;X.fillStyle="#1e3d55";X.fillRect(sx-8,sy-5,16,21);X.fillStyle="#e4ba91";X.fillRect(sx-6,sy-14,12,10);X.fillStyle="#fff";X.fillRect(sx-9,sy-3,18,9)}
function drawBoat(){let sx=P.x*TS-cam.x,sy=P.y*TS-cam.y;X.fillStyle="#7e4e35";X.fillRect(sx-16,sy-4,32,16);X.fillStyle="#e8dfbf";X.fillRect(sx-2,sy-18,4,16);X.beginPath();X.moveTo(sx+2,sy-18);X.lineTo(sx+17,sy-6);X.lineTo(sx+2,sy-6);X.fill()}
function render(){cam.x=clamp(P.x*TS-W/2,0,MW*TS-W);cam.y=clamp(P.y*TS-H/2,0,MH*TS-H);if(P.map==="island")drawIsland();else if(P.map==="sea")drawSea();else drawAbyss();P.map==="sea"?drawBoat():drawPlayer();drawMini()}
function drawMini(){MX.clearRect(0,0,150,100);MX.fillStyle=P.map==="island"?"#d9c58d":P.map==="sea"?"#167e9d":"#06131c";MX.fillRect(0,0,150,100);MX.fillStyle="#fff";MX.fillRect(clamp(P.x/MW*150,2,148),clamp(P.y/MH*100,2,98),4,4);E("weather").textContent=(weather==="SUN"?"☀":weather==="RAIN"?"☂":"⚡")+" "+String(Math.floor(clock)).padStart(2,"0")+":00"}
function near(x,y,r=2){return Math.hypot(P.x-x,P.y-y)<r}
function dialogue(name,text,choices){E("dialogueName").textContent=name.toUpperCase();E("dialogueText").textContent=text;let d=E("dialogueChoices");d.innerHTML="";for(let c of choices){let b=document.createElement("button");b.textContent=c.label;b.onclick=()=>{E("dialogue").classList.add("hidden");c.action?.()};d.appendChild(b)}E("dialogue").classList.remove("hidden")}
function action(){if(fishing.phase==="bite")return hookFish();if(fishing.phase==="fight")return;if(P.map==="island"){if(near(16,18))return fritz();if(near(25,16))return luna();if(near(39,18))return nico();if(near(30,22))return maris();if(near(18,21))return biscuit();if(near(12,16))return skipper();if(P.y>30&&P.x>23&&P.x<31){if(!P.owned.includes("Boat Key"))return toast("The boat is locked. Fritz mentioned a key.");P.map="sea";P.x=27;P.y=34;P.fuel=P.fuelMax||60;P.boat=Math.max(1,P.boat);P.quest=Math.max(P.quest,4);save();return toast("SEAWISP launched")}}else if(P.map==="sea"){if(P.y>35){P.map="island";P.x=27;P.y=30;save();return toast("Back at Fritz Harbor")};if(P.sub&&P.x<6&&P.y<6){P.map="abyss-1";P.x=27;P.y=34;P.quest=Math.max(P.quest,7);save();return toast("DESCENDING — ABYSS FLOOR 1")}}startFishing()}
function fritz(){let total=P.bag.reduce((a,f)=>a+f.value,0);dialogue("Fritz",P.quest===0?"Well look who's back. The sea missed you, kid. Catch a few things and bring them to me.":"Anything worth buying today?",[{label:`Sell catch ₡${total}`,action:()=>sellAll()},{label:"Talk",action:()=>{P.relationships.Fritz++;if(P.quest===0)P.quest=1;save();toast("Fritz trusts you a little more.")}},{label:"Later"}])}
function sellAll(){let total=P.bag.reduce((a,f)=>a+f.value,0);if(!total)return toast("Your pack is empty.");P.money+=total;P.bag=[];if(P.caught>=3)P.quest=Math.max(P.quest,2);save();hud();toast(`Sold catch for ₡${total}`)}
function luna(){if(P.quest<2)return dialogue("Luna","Fritz says you're new. Bring him a few catches first.",[{label:"Okay"}]);dialogue("Luna","Tackle decides what kind of fisher you become.",[{label:"Shop",action:()=>shop("LUNA'S TACKLE",ITEMS.filter(i=>["rod","bag","bait","tool","gift"].includes(i.type)&&i.tier<=Math.max(2,P.level)))},{label:"Talk",action:()=>{P.relationships.Luna++;save();toast("Luna relationship +1")}},{label:"Later"}])}
function nico(){dialogue("Nico","If it floats, I can improve it. If it sinks, Maris probably wants it.",[{label:"Shipyard",action:()=>shop("NICO'S SHIPYARD",ITEMS.filter(i=>["key","boat","engine","sonar","sub","fuel"].includes(i.type)))},{label:"Talk",action:()=>{P.relationships.Nico++;save();toast("Nico relationship +1")}},{label:"Later"}])}
function maris(){dialogue("Maris","Every depth has its own ecosystem. The Abyss isn't empty — that's the problem.",[{label:"Research Gear",action:()=>shop("MARIS RESEARCH",ITEMS.filter(i=>["map","charm","tool","weapon","knife"].includes(i.type)))},{label:"Talk",action:()=>{P.relationships.Maris++;save();toast("Maris relationship +1")}},{label:"Later"}])}
function biscuit(){P.relationships.Biscuit++;save();toast("Biscuit wags his tail. Relationship +1")}
function skipper(){P.relationships.Skipper++;save();toast("Skipper judges you silently. Relationship +1")}
function shop(title,list){let h=`<h2>${title}</h2><div class="shopGrid">`;for(let i of list){let own=P.owned.includes(i.name)&&!["fuel","consumable","gift"].includes(i.type);h+=`<div class="shopItem"><b>${i.name}</b><small>${i.type.toUpperCase()} · T${i.tier}</small><p>${i.desc}</p><strong>₡${i.price}</strong><button ${own?"disabled":""} data-buy="${i.name.replaceAll('"','&quot;')}">${own?"OWNED":"BUY"}</button></div>`}h+="</div><button id='closeShop'>CLOSE</button>";E("modal").innerHTML=h;E("modalWrap").classList.remove("hidden");E("closeShop").onclick=()=>E("modalWrap").classList.add("hidden");E("modal").querySelectorAll("[data-buy]").forEach(b=>b.onclick=()=>buy(b.dataset.buy))}
function buy(name){let i=ITEMS.find(x=>x.name===name);if(!i||P.money<i.price)return toast("Not enough credits.");P.money-=i.price;if(i.type==="fuel"){P.fuel=Math.min(P.fuelMax||60,P.fuel+(i.name.includes("Large")?50:20))}else if(i.type==="consumable"){if(i.name==="Med Kit")P.hp=Math.min(P.hpMax,P.hp+55)}else if(i.type==="gift"){}else{P.owned.push(i.name);if(i.type==="bag")P.bagCap+={"Small Backpack":6,"Canvas Pack":8,"Deck Pack":10,"Expedition Pack":14}[i.name];if(i.type==="rod")P.rod=Math.max(P.rod,i.tier);if(i.type==="knife")P.knife=Math.max(P.knife,i.tier);if(i.type==="weapon")P.weapon=Math.max(P.weapon,i.tier);if(i.name==="Boat Key"){P.fuelMax=60;P.quest=Math.max(P.quest,3)}if(i.type==="boat"){P.boat=Math.max(P.boat,i.tier);P.fuelMax=Math.max(P.fuelMax,60+i.tier*25)}if(i.type==="engine")P.fuelMax+=20;if(i.type==="sub")P.sub=true}save();hud();toast(`${i.name} acquired`);E("modalWrap").classList.add("hidden")}
function inventory(){let h=`<h2>${P.name}'s Pack</h2><p>Credits: ₡${Math.floor(P.money)}</p><div class="inventoryList">`;let counts={};P.bag.forEach(f=>counts[f.name]=(counts[f.name]||0)+1);for(let [n,c] of Object.entries(counts))h+=`<div>${n}<b>x${c}</b></div>`;h+=`</div><h3>Gear</h3><div class="owned">${P.owned.map(x=>`<span>${x}</span>`).join("")}</div><button id="closeInv">CLOSE</button>`;E("modal").innerHTML=h;E("modalWrap").classList.remove("hidden");E("closeInv").onclick=()=>E("modalWrap").classList.add("hidden")}
function pickFish(){return choice(fishPool())}
function startFishing(){if(P.bag.length>=P.bagCap)return toast("Pack full. Sell your catch.");if(!waterAhead())return toast("Face the water.");fishing={phase:"waiting",fish:pickFish(),wait:rnd(.65,P.owned.includes("Bait Box")?1.2:1.8),distance:1,tension:.26,reel:false};E("fishingUI").classList.remove("hidden");E("fishName").textContent="CASTING";E("fishMessage").textContent="Wait for a bite..."}
function updateFishing(dt){if(fishing.phase==="idle")return;if(fishing.phase==="waiting"){fishing.wait-=dt;if(fishing.wait<=0){fishing.phase="bite";fishing.wait=1.25;E("fishName").textContent="BITE!";E("fishMessage").textContent="Tap ACTION now!"}return}if(fishing.phase==="bite"){fishing.wait-=dt;if(fishing.wait<=0){fishing.phase="idle";E("fishingUI").classList.add("hidden");toast("Too slow.")}return}if(fishing.phase==="fight"){let f=fishing.fish,bonus=P.owned.includes("Quick-Reel Module")?.04:0;if(fishing.reel){fishing.distance-=dt*(.18+P.rod*.035+bonus);fishing.tension+=dt*(.31+f.zone*.035)}else{fishing.distance+=dt*(.025+f.zone*.008);fishing.tension-=dt*(.27+(P.owned.includes("Auto-Balancer")?.05:0))}fishing.tension=clamp(fishing.tension,.04,1.15);E("tensionFill").style.width=clamp(fishing.tension,0,1)*100+"%";E("distanceFill").style.width=clamp(fishing.distance,0,1)*100+"%";if(fishing.tension>1.02){fishing.phase="idle";E("fishingUI").classList.add("hidden");return toast("SNAP! The line broke.")}if(fishing.distance>1.1){fishing.phase="idle";E("fishingUI").classList.add("hidden");return toast("It escaped.")}if(fishing.distance<=.02)beginBattle(f)}}
function hookFish(){if(fishing.phase!=="bite")return;fishing.phase="fight";fishing.tension=.34;fishing.distance=.96;E("fishName").textContent=fishing.fish.name.toUpperCase();E("fishMessage").textContent="Hold ACTION to reel. Release before tension maxes out."}
function beginBattle(f){fishing.phase="idle";E("fishingUI").classList.add("hidden");battle={fish:f,enemyHp:f.hp,enemyMax:f.hp,turn:"player"};E("battle").classList.remove("hidden");E("enemyName").textContent=f.name;E("enemyHpMax").textContent=f.hp;E("playerBattleName").textContent=P.name;E("playerHpMax").textContent=P.hpMax;battleMenu();battleHud()}
function battleHud(){if(!battle)return;E("playerHp").textContent=Math.max(0,Math.ceil(P.hp));E("playerHpFill").style.width=clamp(P.hp/P.hpMax,0,1)*100+"%";E("enemyHp").textContent=Math.max(0,Math.ceil(battle.enemyHp));E("enemyHpFill").style.width=clamp(battle.enemyHp/battle.enemyMax,0,1)*100+"%";E("focus").textContent=P.focus}
function battleMenu(){let m=E("moves");m.innerHTML="";let moves=[{n:"REEL STRIKE",d:8+P.rod*3},{n:"KNIFE CUT",d:10+P.knife*4},{n:"HARPOON",d:12+P.weapon*5},{n:"FOCUS",d:6+Math.floor(P.focus/5)}];moves.forEach((mv,i)=>{let b=document.createElement("button");b.textContent=mv.n;b.disabled=i===1&&!P.owned.some(x=>x.includes("Knife")||x.includes("Blade"))||i===2&&!P.owned.some(x=>["Harpoon","Speargun","Spear","Lance","Launcher","Pistol"].some(k=>x.includes(k)));b.onclick=()=>startTiming(mv);m.appendChild(b)})}
function startTiming(move){if(!battle||timing)return;timing={move,pos:0,dir:1,speed:.9+rnd(0,.45)};E("timingBar").classList.remove("hidden");E("moves").classList.add("hidden");E("battleMessage").textContent="Tap A in the center!"}
function resolveTiming(){if(!timing||!battle)return;let p=timing.pos,acc=1-Math.min(1,Math.abs(p-.5)*2),mult=acc>.82?1.8:acc>.55?1.3:.75,dmg=Math.round(timing.move.d*mult);battle.enemyHp-=dmg;P.focus=Math.min(100,P.focus+(acc>.7?8:3));E("battleMessage").textContent=`${timing.move.n}: ${dmg} damage`;timing=null;E("timingBar").classList.add("hidden");E("moves").classList.remove("hidden");battleHud();if(battle.enemyHp<=0)return winBattle();setTimeout(enemyTurn,450)}
function enemyTurn(){if(!battle)return;let f=battle.fish,mit=P.owned.includes("Pressure Amulet")?3:0,d=Math.max(1,Math.round(f.atk*rnd(.7,1.15)-mit));P.hp-=d;E("battleMessage").textContent=`${f.name} hits for ${d}`;battleHud();if(P.hp<=0){P.hp=P.hpMax;P.money=Math.floor(P.money*.9);P.map="island";P.x=25;P.y=20;E("battle").classList.add("hidden");battle=null;save();return toast("You washed up at Fritz Harbor.")}setTimeout(()=>{E("battleMessage").textContent="Your turn.";battleMenu()},450)}
function winBattle(){let f=battle.fish;P.bag.push({...f});P.caught++;P.xp+=f.xp+(P.owned.includes("Compass Charm")?3:0);P.money+=Math.floor(f.value*.08);P.seen[f.name]=(P.seen[f.name]||0)+1;while(P.xp>=P.level*75){P.xp-=P.level*75;P.level++;P.hpMax+=8;P.hp=P.hpMax;toast(`LEVEL ${P.level}!`)}if(P.quest===1&&P.caught>=3)P.quest=2;E("battle").classList.add("hidden");battle=null;save();hud();toast(`Caught ${f.name} · value ₡${f.value}`)}
function drawPortraits(){let pc=E("playerPortrait"),ec=E("enemyPortrait"),p=pc.getContext("2d"),e=ec.getContext("2d");p.clearRect(0,0,160,160);e.clearRect(0,0,160,160);p.fillStyle="#102533";p.fillRect(0,0,160,160);p.fillStyle="#e1b18b";p.beginPath();p.arc(80,66,32,0,Math.PI*2);p.fill();p.fillStyle="#453026";p.fillRect(45,35,70,25);p.fillStyle="#fff";p.fillRect(44,100,72,50);if(!battle)return;e.fillStyle="#06141d";e.fillRect(0,0,160,160);e.fillStyle="#4fc3cf";e.beginPath();e.ellipse(80,80,55,29,0,0,Math.PI*2);e.fill();e.fillStyle="#0d2831";e.beginPath();e.moveTo(128,80);e.lineTo(155,58);e.lineTo(155,102);e.fill();e.fillStyle="#fff";e.fillRect(49,69,6,6)}
function update(dt){clock=(clock+dt*.12)%24;if(Math.floor(clock)%6===0&&Math.random()<dt*.02)weather=choice(["SUN","RAIN","STORM"]);if(battle||fishing.phase!=="idle"||!J.on)return;let speed=P.map==="island"?3.1:P.map==="sea"?2.8+P.boat*.12:2.5,nx=P.x+J.x*speed*dt,ny=P.y+J.y*speed*dt;if(P.map==="island"){if(!blocked(nx,P.y))P.x=nx;if(!blocked(P.x,ny))P.y=ny}else{P.x=clamp(nx,1,MW-2);P.y=clamp(ny,1,MH-1);if(P.map==="sea"){P.fuel=Math.max(0,P.fuel-dt*(.8+P.boat*.08)*(weather==="STORM"?1.7:1));if(P.fuel<=0){P.map="island";P.x=27;P.y=33;toast("OUT OF FUEL — TOWED HOME");save()}}}if(Math.abs(J.x)>Math.abs(J.y)&&Math.abs(J.x)>.15)face={x:Math.sign(J.x),y:0};else if(Math.abs(J.y)>.15)face={x:0,y:Math.sign(J.y)}}
function loop(t){let dt=Math.min(.035,(t-last)/1000||0);last=t;update(dt);updateFishing(dt);if(timing){timing.pos+=timing.dir*timing.speed*dt;if(timing.pos>=1){timing.pos=1;timing.dir=-1}else if(timing.pos<=0){timing.pos=0;timing.dir=1}E("timingNeedle").style.left=timing.pos*100+"%"}X.clearRect(0,0,W,H);render(t);drawPortraits();hud();requestAnimationFrame(loop)}
const joy=E("joystick"),knob=E("joystickKnob");joy.addEventListener("pointerdown",e=>{e.preventDefault();J.on=true;J.id=e.pointerId;joy.setPointerCapture?.(e.pointerId)});joy.addEventListener("pointermove",e=>{if(!J.on||e.pointerId!==J.id)return;let r=joy.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,l=Math.hypot(dx,dy),m=47;if(l>m){dx*=m/l;dy*=m/l}J.x=dx/m;J.y=dy/m;knob.style.transform=`translate(${dx}px,${dy}px)`});function endJoy(){J.on=false;J.x=J.y=0;knob.style.transform="translate(0,0)"}joy.addEventListener("pointerup",endJoy);joy.addEventListener("pointercancel",endJoy);
E("actionBtn").addEventListener("pointerdown",e=>{e.preventDefault();if(fishing.phase==="fight")fishing.reel=true});E("actionBtn").addEventListener("pointerup",e=>{e.preventDefault();if(fishing.phase==="fight")fishing.reel=false;else action()});E("packBtn").onclick=inventory;E("timingButton").onclick=resolveTiming;
function startGame(loadSave){if(loadSave)load();else{Object.assign(P,{name:(E("playerName").value.trim()||"Kai").slice(0,14),map:"island",x:25,y:20,money:0,bag:[],bagCap:10,caught:0,hp:100,hpMax:100,focus:0,xp:0,level:1,quest:0,owned:["Bamboo Rod"],rod:0,knife:0,weapon:0,boat:0,fuel:0,fuelMax:0,sub:false,store:false,workshop:false,relationships:{Fritz:0,Luna:0,Nico:0,Maris:0,Biscuit:0,Skipper:0},flags:{},seen:{}});save()}E("startScreen").classList.add("hidden");E("hud").classList.remove("hidden");E("minimap").classList.remove("hidden");E("joystick").classList.remove("hidden");E("worldButtons").classList.remove("hidden");hud();resize();last=performance.now();requestAnimationFrame(loop)}
E("startBtn").onclick=()=>startGame(false);if(localStorage.getItem(saveKey))E("continueBtn").classList.remove("hidden");E("continueBtn").onclick=()=>startGame(true);document.addEventListener("contextmenu",e=>e.preventDefault());document.addEventListener("selectstart",e=>{if(e.target!==E("playerName"))e.preventDefault()});resize();hud();
})();